[tools]
"npm:@modelcontextprotocol/inspector" = "0.10.2" # install mcp-inspector command

[tasks]
[tasks.dev]
run = "mcp-inspector -- v run ."

[tasks.dev-cli]
run = "mcp-inspector --cli --method tools/list -- v run ."